### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by ShamHyper** [NoyWasTaken/TF2_VIP#15]
I have 3 errors to you, dev!

1. When entering sm_addvip instead of executing a command, the plugin writes how to use it
I enter /addvip STEAM_0:0:176219724 7 or in the console, does not work
2. The link to sounds is outdated
3. Australium erroring:
```php
L 11/11/2023 - 01:41:17: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/11/2023 - 01:41:17: [SM] Blaming: VIP_Perks/VIP_Australium.smx
L 11/11/2023 - 01:41:17: [SM] Call stack trace:
L 11/11/2023 - 01:41:17: [SM]   [0] GetEntProp
L 11/11/2023 - 01:41:17: [SM]   [1] Line 285, C:\Users\Noy\Desktop\Git\TF2_VIP\VIP_Perks\VIP_Australium.sp::getAmmo
L 11/11/2023 - 01:41:17: [SM]   [2] Line 190, C:\Users\Noy\Desktop\Git\TF2_VIP\VIP_Perks\VIP_Australium.sp::giveAustraliums
L 11/11/2023 - 01:41:17: [SM]   [3] Line 63, C:\Users\Noy\Desktop\Git\TF2_VIP\VIP_Perks\VIP_Australium.sp::Event_PlayerRegen
L 11/11/2023 - 01:41:17: [SM]   [5] TF2_RespawnPlayer
L 11/11/2023 - 01:41:17: [SM]   [6] Line 48, /home/forums/content/files/2/4/3/2/0/6/136289.attach::Respawn
```

**Comment by NoyWasTaken** [comment]
Hey,
1. Use the console with this syntax: sm_addvip "STEAM_0:0:176219724" 7 - if you're trying to pass the steamid in the chat it won't recognize it as a single string argument.
2. I've updated the README file with a new link to download the sounds.
3. I'll check the issue as soon as I can and will keep you updated.

**Comment by q1085909155** [comment]
For question 3: Maybe you are not using the latest update version, this error has appeared when I used the old version, after using the new version, this error has been cancelled

**Comment by ShamHyper** [comment]
> For question 3: Maybe you are not using the latest update version, this error has appeared when I used the old version, after using the new version, this error has been cancelled

I using latest release

**Comment by ShamHyper** [comment]
> Hey,
> 
> 1. Use the console with this syntax: sm_addvip "STEAM_0:0:176219724" 7 - if you're trying to pass the steamid in the chat it won't recognize it as a single string argument.
> 2. I've updated the README file with a new link to download the sounds.
> 3. I'll check the issue as soon as I can and will keep you updated.

1. I'll check tomorrow
2. Thx
3. Okey
