### ISSUE TITLE
Multiplaying chat messages

### ISSUE THREAD

**Issue by Miciasty** [NoyWasTaken/TF2_VIP#17]
![image](https://github.com/NoyWasTaken/TF2_VIP/assets/108985589/c8afe1f7-abe3-4e5d-8fa8-9407b53ce6c0)

When people with vip tag [sm_vip_admins 1] are sending messages they are multiplaying.

**Comment by NoyWasTaken** [comment]
Hey,
Are there any other plugins running on the server that modify the chat?
I don't see any reason that the plugin will make this print but I'll investigate it.

**Comment by Miciasty** [comment]
Hey, sorry for the last response. i didnt get any notify. No there aren't more plugins than yours, except the default from SourceMod

**Comment by NoyWasTaken** [comment]
Can you make sure you're using the latest version of the plugin?
The release here was outdated so if you didn't compile the plugin yourself it would have been outdated.
