### ISSUE TITLE
Is the plugin still in maintenance?

### ISSUE THREAD

**Issue by q1085909155** [NoyWasTaken/TF2_VIP#6]
This is a great plugin , can you continue to maintain and update it? I have a request: 
1. Set its database encoding to UTF8. 
2. After the player joins the game, if he is a vip, update the database name field.
3. Change the expiration field format to yyyy-MM-dd HH:mm:ss

**Comment by NoyWasTaken** [comment]
I've pushed into the `develop` branch updates for the first two requests.
Will validate and merge them later
I'll check about the expiration field format but I believe I can change it's type to be `datetime` but it'll required some adjustments in the code (I'll also need to check that it won't cause issues).

**Comment by NoyWasTaken** [comment]
> You're a great programmer. Thank you for supporting your plugins If possible, I hope you can do more vip features.

You can always suggest and I'll add.


> ![image](https://user-images.githubusercontent.com/69096633/212743941-ba964d52-d589-4bee-bc88-cf35baf59aee.png) Sometimes it causes my server to crash, but I'm not sure if that's the reason

I've pushed a fix, will merge it soon with the other fixes / updates.
