### ISSUE TITLE
More requests and questions

### ISSUE THREAD

**Issue by q1085909155** [NoyWasTaken/TF2_VIP#8]
After my testing, I remembered some residual problems
1.The sm addvip command is not available in the console, which makes it difficult for me to work outside, but when a player needs to become a vip，As well as using formatting errors in the game, for example I used sm addvip "STEAM_0:1:243826165" 10 which will not be valid
2.The database field needs to be updated with a given time and the expired field changed to the format yyyy-MM-dd HH:mm:ss
3.manage vips → remove vip Invalid after use

**Comment by q1085909155** [comment]
Sorry for my poor English, the second point means that we need to add a new field called Add time, which records the time when players are given vip

**Comment by q1085909155** [comment]
![image](https://user-images.githubusercontent.com/69096633/212829097-f287aaa0-c421-4073-a420-42c3079a0a51.png)
We need to use the format yyyy-MM-dd HH:mm:ss

**Comment by q1085909155** [comment]
Compilation doesn't seem to work in 1.11
![image](https://user-images.githubusercontent.com/69096633/212829612-8f08100e-62e9-4df6-8654-829da9980e57.png)

**Comment by NoyWasTaken** [comment]
I've fixed the issue with the "addvip" command (also allowed it's usage from console).
The manage vip menu is also fixed.
About the expiration column I'll update it in the future when I'll have more free time.

**Comment by NoyWasTaken** [comment]
> Compilation doesn't seem to work in 1.11 ![image](https://user-images.githubusercontent.com/69096633/212829612-8f08100e-62e9-4df6-8654-829da9980e57.png)

I compiled with sm 1.11 (6927) and everything works fine.
Are you sure you're compiling with the latest version of spcomp? This looks more like errors of sm 1.9

**Comment by q1085909155** [comment]
ok, sorry, maybe mine is broken, you can ignore it, I will use a new one to replace it. Next is waiting for your update
